<?php

/**
 * This file is automatically generated. Use 'bin/celerity map' to rebuild it.
 *
 * @generated
 */
return array(
  'names' => array(
    'js/junkpile-alert.js' => 'f9ed6a68',
  ),
  'symbols' => array(
    'javelin-behavior-junkpile-alert' => 'f9ed6a68',
  ),
  'requires' => array(),
  'packages' => array(),
);
